### ISSUE TITLE
AVRCP 1.6 "Out of bounds" settings crash

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#11]
*Device*: Xiaomi Redmi Note 5
*ROM*: 8.12.13

So, I was trying to set AVRCP 1.6 in `Developer settings`, but it looks like I am unable to do because of problem. Screenshot below:
![Error screenshot](https://user-images.githubusercontent.com/42800753/50047328-8dd5e380-00bb-11e9-8eae-c29f29d7c169.png)

**Comment by mclaude74** [comment]
Fix added in [cffb9af](https://github.com/ingbrzy/MA-XML-10-RUSSIAN/commit/cffb9af9ee7e64f7d0fd5bf3fab753e2e2e70387#diff-f4d2df24a1a7409a691754a843f993fc)

**Comment by Kugumin** [comment]
Thanks for fix!
