### ISSUE TITLE
Translation of menu items

### ISSUE THREAD

**Issue by dmgurov** [ingbrzy/MA-XML-10-RUSSIAN#16]
Lost Russian translation here:
Settings --- Additional Settngs --- Button and gesture shortcuts --- **Al button** --- 

Al button = AI кнопка
Press AI BUTTON = Нажмите AI кнопку
PRESS AND HOLD AI BUTTON = Нажмите и удерживайте AI кнопку
DOUBLE PRESS AI BUTTON = Двойное нажатие на AI кнопку

**Comment by ingbrzy** [comment]
Fix by https://github.com/ingbrzy/MA-XML-10-RUSSIAN/commit/9e1506ea98575e04eee8548050af3d44e59b3824

**Comment by dmgurov** [comment]
Im sorry, and one more question about translation (I think that it is only for Mi Mix 3):
Settings --- **Slider settings**

Slider shortcut (Push the screen down to take a selfie)
Take a selfie
Open tools
Open app
None

Sounds (Play sounds when you slide the screen up and down)

**Comment by mclaude74** [comment]
Добавлено. Перевод попадет в сборку, скорее всего, через неделю.
