### ISSUE TITLE
Non-translated mobile data warning

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#20]
![screenshot_2018-12-20-08-59-07-254_com android providers downloads](https://user-images.githubusercontent.com/42800753/50273793-485f4080-0444-11e9-89e4-bbe477707062.png)

**Comment by mclaude74** [comment]
Добавил перевод в своей копии репозитория, но на данный момент основной репозиторий недоступен для слияния. Надеюсь, позже будет доступен. Думаю, репозиторий закрыт на момент сборки прошивок :)
