### ISSUE TITLE
Translation not yet at Settings , Updates and others 

### ISSUE THREAD

**Issue by Axund** [ingbrzy/MA-XML-10-RUSSIAN#23]
Hello . i put here screenshots of not yet translations .

**Comment by Axund** [comment]
![image](https://user-images.githubusercontent.com/46032453/50305125-6ca23800-04ab-11e9-9544-9a77bffcc7ac.png)
![image](https://user-images.githubusercontent.com/46032453/50305162-7cba1780-04ab-11e9-9cfd-f1c3fbe204a7.png)
![image](https://user-images.githubusercontent.com/46032453/50305178-85aae900-04ab-11e9-9a7b-46697e1b8fae.png)
![image](https://user-images.githubusercontent.com/46032453/50305193-8e9bba80-04ab-11e9-842d-2b184134f209.png)
![image](https://user-images.githubusercontent.com/46032453/50305215-978c8c00-04ab-11e9-8ca4-b20576683145.png)
![image](https://user-images.githubusercontent.com/46032453/50305225-9e1b0380-04ab-11e9-8ba8-7a4034842f06.png)
![image](https://user-images.githubusercontent.com/46032453/50305238-a4a97b00-04ab-11e9-9009-5c7e29569679.png)

**Comment by mclaude74** [comment]
Alteady translated.

Уже переведено. В текущей еженедельной перевод пунктов из Настроек и Рабочего стола есть. 
В следующей д.б. 
+Обновление 
+Экран блокировки (левая панель)
+Проводник
+Расширенное меню перезагрузки
+Безопасность
+Загрузки
+Мое устройство (таблица)
+Ассистент (Лента виджетов)
+Браузер
