### ISSUE TITLE
Fullscreen mode warning

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#24]
![screenshot_2018-12-22-18-19-56-697_com andromeda androbench2](https://user-images.githubusercontent.com/42800753/50376765-c2492280-061a-11e9-927a-13258934918f.png)

**Comment by mclaude74** [comment]
@ingbrzy 
"aspect_message" and other "aspect_" absent in MIUISystemUI strings.xml for some devices.
Can I add these lines to this repository?

**Comment by ingbrzy** [comment]
yes you can add them.. will be ignored at device where are not used...

**Comment by mclaude74** [comment]
@Kugumin 
[Added](https://github.com/ingbrzy/MA-XML-10-RUSSIAN/blob/77c91e337a8447ea5fe22158a3b3642f61031846/Russian/main/MiuiSystemUI.apk/res/values-ru/strings.xml#L287-L290).
