### ISSUE TITLE
Translation in Settings.apk

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-10-RUSSIAN#26]
@Kugumin 
Зафиксировал правку:
"Размер экрана" --> "Диагональ"
Поправил:
"Емкость акумулятора" --> "Аккумулятор", т.к. не вписывается.
Остальные строки на моем устройстве вписываются, но можно и сократить.
"Разрешение экрана" --> "Разрешение", "Оперативная память" --> "Память".
Ваше мнение по этому поводу?

**Comment by Kugumin** [comment]
Думаю лучше переименовать оперативную память в `ОЗУ`

**Comment by mclaude74** [comment]
ОЗУ - хороший вариант.
"Разрешение экрана" оставляем или сокращаем?

**Comment by Kugumin** [comment]
Да, тоже сократить можно

**Comment by mclaude74** [comment]
Благодарю за мнение
