### ISSUE TITLE
Different words case

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#30]
I think case of word `Удалить` should be set to upper. (Right bottom corner)
![screenshot_2018-12-28-15-40-34-425_lockscreen](https://user-images.githubusercontent.com/42800753/50517115-50a82300-0ab7-11e9-9207-25e03221291d.png)

**Comment by mclaude74** [comment]
"Удалить" берется из другого ресурса, пока не могу сказать точно откуда.
Остальные строки находятся [здесь](https://github.com/ingbrzy/MA-XML-10-RUSSIAN/blob/311eeed424b9d08803a4e1e5e6cd317b52bf8ee3/Russian/extras/powermenu/strings/strings_ru_RU.xml#L8-L9).
Переведу их в нижний регистр, если ingbrzy не подскажет, где расположено "Удалить" и используется ли в других местах.

**Comment by mclaude74** [comment]
Сделал "Экстренный вызов" в нижнем регистре, но в текущей сборке по прежнему в верхнем. Либо правки не попали в сборку, либо ещё что-то.
