### ISSUE TITLE
Fullscreen mode string in app settings

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#31]
![screenshot_2018-12-30-09-45-49-162_com miui securitycenter](https://user-images.githubusercontent.com/42800753/50545308-f672a380-0c17-11e9-8312-07f6d26e3446.png)

**Comment by mclaude74** [comment]
[Добавил](https://github.com/ingbrzy/MA-XML-10-RUSSIAN/blob/84c135f7bdab145c0814359bb814747ffafdd8a2/Russian/main/SecurityCenter.apk/res/values-ru/strings.xml#L2148-L2149) перевод.
