### ISSUE TITLE
Alarm clock app

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#32]
Words `hours` and `minutes` aren't translated. Somehow they were translated in previous versions of EU ROMs
![screenshot_2019-01-01-01-30-39-546_com android deskclock](https://user-images.githubusercontent.com/42800753/50569031-46ab4c00-0d65-11e9-927c-5811f6b28c43.png)

**Comment by mclaude74** [comment]
![screenshot_2019-01-02-02-32-04-800_com android deskclock](https://user-images.githubusercontent.com/45774262/50577337-5abf7e00-0e37-11e9-9fca-dd64d3ea3887.png)
В моем случае часы и минуты корректно отображаются. Но попробую поискать.

**Comment by mclaude74** [comment]
Ставил прошивку с вайпами кэш/далвик?

**Comment by mclaude74** [comment]
Файл plurals.xml переведен полностью,
[строки часы/минуты/секунды присутствуют](https://github.com/ingbrzy/MA-XML-10-RUSSIAN/blob/84c135f7bdab145c0814359bb814747ffafdd8a2/Russian/main/DeskClock.apk/res/values-ru/plurals.xml#L37-L54)

**Comment by mclaude74** [comment]
[Добавил](https://github.com/ingbrzy/MA-XML-10-RUSSIAN/blob/ca67cdc489e92b5167ea63648e8402209fdd6a42/Russian/main/DeskClock.apk/res/values-ru/plurals.xml#L55-L65) в сокращенном написании. Если будет не очень, заменю на полное написание (надо будет открыть новую заявку). В моем случае, видимо, используются другие переменные - hours и minutes из файла strings.xml
