### ISSUE TITLE
Mi Explorer 

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#33]
![img_20190102_190201](https://user-images.githubusercontent.com/42800753/50602857-41fbaa80-0ec1-11e9-9f6b-74e212f81a61.jpg)

**Comment by mclaude74** [comment]
[Добавлено](https://github.com/ingbrzy/MA-XML-10-RUSSIAN/blob/cdd3caf49ab4f679459c58fc56ca08ce5ac43770/Russian/main/FileExplorer.apk/res/values-ru/plurals.xml#L15-L25).
