### ISSUE TITLE
Alarm clock app again

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#36]
![screenshot_2019-01-03-21-31-35-947_com android deskclock](https://user-images.githubusercontent.com/42800753/50659447-51ecba80-0fa5-11e9-8566-7747460f8849.png)
![screenshot_2019-01-03-21-31-42-472_com android deskclock](https://user-images.githubusercontent.com/42800753/50659448-51ecba80-0fa5-11e9-9f8f-6f289d736e44.png)

**Comment by mclaude74** [comment]
Интересно то, что у меня этот пункт в виде меню, всё переведено.
Возможно из-за того, что у тебя 8.1 версия Android, у меня 9й.
Добавлю перевод, как представится возможность

**Comment by mclaude74** [comment]
Вариант перевода:
Snooze - Повтор сигнала
Interval (minutes) - Интервал (минуты)
Times - Число повторов.

На моём телефоне только интервал можно задать.

**Comment by Kugumin** [comment]
Было переведено при слиянии #37
