### ISSUE TITLE
Updater app

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#38]
Как ни странно строки, отвечающие за перевод этих строк есть, но сам перевод не отображается. Проверял так же на украинском языке и там была та же самая проблема
![screenshot_2019-01-03-22-55-41-038_pl zdunex25 updater](https://user-images.githubusercontent.com/42800753/50661391-ac891500-0fab-11e9-94b2-c110eb87e272.png)

**Comment by mclaude74** [comment]
Видимо изменили имя переменной, т.к. раньше был перевод.

Ну и в Проводнике есть проблемы с недопереводом и пробелоами между словами.

**Comment by mclaude74** [comment]
@ingbrzy, we have already translated "weekly", and in previous builds the translation was displayed correctly, in this build again in English. Why?
