### ISSUE TITLE
DocumentsUI (or "Files")

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#39]
Так же было сообщение об ошибке удаления файла, но к сожалению не сделал его скриншот
![screenshot_2019-01-03-23-34-50-761_com android documentsui](https://user-images.githubusercontent.com/42800753/50662771-3aff9580-0fb0-11e9-8b74-f0dc31fc4d1b.png)
![screenshot_2019-01-03-23-33-30-630_com android documentsui](https://user-images.githubusercontent.com/42800753/50662772-3aff9580-0fb0-11e9-8e1c-a971a506c22d.png)
![screenshot_2019-01-03-23-33-33-103_com android documentsui](https://user-images.githubusercontent.com/42800753/50662773-3aff9580-0fb0-11e9-9260-678c180dbcc8.png)
![screenshot_2019-01-03-23-33-36-638_com android documentsui](https://user-images.githubusercontent.com/42800753/50662774-3aff9580-0fb0-11e9-8e90-08b0273f9a40.png)
![screenshot_2019-01-03-23-33-39-821_com android documentsui](https://user-images.githubusercontent.com/42800753/50662775-3b982c00-0fb0-11e9-82ac-437770241f9d.png)
![screenshot_2019-01-03-23-33-46-330_com android documentsui](https://user-images.githubusercontent.com/42800753/50662776-3b982c00-0fb0-11e9-9f44-45093bf4b227.png)
![screenshot_2019-01-03-23-33-48-961_com android documentsui](https://user-images.githubusercontent.com/42800753/50662777-3b982c00-0fb0-11e9-8459-1c41b0757404.png)

**Comment by mclaude74** [comment]
Внёс твои правки в базу. По идее, эту заявку можно закрыть

**Comment by mclaude74** [comment]
Добавлю тебя в список соавторов перевода, если не возражаешь (Настройки / Мое устройство / Авторы перевода)
:)

**Comment by Kugumin** [comment]
Конечно я не против, я даже рад, что я хоть где-то упоминаюсь 😄

Закрываю заявку.
