### ISSUE TITLE
Ошибка перевода заряда и состояния Bluetooth гарнитур

### ISSUE THREAD

**Issue by Kugumin** [ingbrzy/MA-XML-10-RUSSIAN#51]
Отображается так:
![image](https://user-images.githubusercontent.com/42800753/58544644-5b074e00-820a-11e9-8e8a-3cce33299d60.png)
А должно быть вот: 
![image](https://user-images.githubusercontent.com/42800753/58544658-635f8900-820a-11e9-9223-6ab4f5344dea.png)
Ну, или хотя-бы быть без ошибки

**Comment by mclaude74** [comment]
В английском варианте тоже без пробела. Добавил пробел в переводе.
https://github.com/ingbrzy/MA-XML-10-RUSSIAN/blob/e182ff60b13a493201abca9db4bdeb0161c34bd6/Russian/main/MiuiSystemUI.apk/res/values-ru/strings.xml#L339

**Comment by mclaude74** [comment]
@Kugumin, изменилась ли ситуация в 9.5.30 ?

**Comment by mar1k94** [comment]
![Screenshot_2019-08-02-09-08-03-234_com android chrome](https://user-images.githubusercontent.com/8592709/62348237-1c8d5880-b505-11e9-84b6-30da0984991f.jpg)
всё так же

**Comment by mclaude74** [comment]
@mar1k94 
Если переключиться на английский язык, отображение корректное?

**Comment by mar1k94** [comment]
> @mar1k94
> Если переключиться на английский язык, отображение корректное?
да
![Screenshot_2019-08-02-17-53-48-011_com android settings](https://user-images.githubusercontent.com/8592709/62406161-d93bf400-b5af-11e9-9c80-8af1f0e54527.jpg)

**Comment by mclaude74** [comment]
@mar1k94 
Спасибо, посмотрю в чем может быть дело.

**Comment by mclaude74** [comment]
@ingbrzy 

Ingbrzy, please help solve the problem.
A translation for the state of bluetooth in Russian is present, but the display is incorrect (first and third screenshots). In English, the display is correct. 

English language:
https://github.com/ingbrzy/Xiaomi.eu-MIUIv10-XML-Compare/blob/614aef29a30e49631190fc32c72ff70c287bb327/nitrogen/MiuiSystemUI.apk/res/values/strings.xml#L376-L384

Russian language:
https://github.com/ingbrzy/MA-XML-10-RUSSIAN/blob/ba33f1906d37eb67c425571c2967a1ffdc525a11/Russian/main/MiuiSystemUI.apk/res/values-ru/strings.xml#L339-L347

**Comment by mclaude74** [comment]
Most likely, the strings in the English repository are also incorrect. Took as sample strings from the Slovak repository. Hope this solves the problem.

**Comment by mclaude74** [comment]
@mar1k94
В версии 9.8.8 ситуация изменилась?

**Comment by mar1k94** [comment]
> @mar1k94
> В версии 9.8.8 ситуация изменилась?

Да, вот скриншот
![Screenshot_2019-08-10-07-16-09-177_com hil_hk xsection](https://user-images.githubusercontent.com/8592709/62826813-490f3780-bbcb-11e9-8626-9834856c25f1.jpg)

**Comment by mclaude74** [comment]
> Да, вот скриншот

Спасибо. Перевод делался на основе английского репозитория, там не актуальные строки. Взял за основу строки из словацкого репозитория (родной для xiaomi.eu). 
Закрываю тикет.
