### ISSUE TITLE
Недоперевод

### ISSUE THREAD

**Issue by Glocksss** [ingbrzy/MA-XML-10-RUSSIAN#54]
Привет, большой недоперевод последней еженедельной, скажи есть ли возможность какого нибудь патча или перезалить прошивку с переводом, заранее спасибо

**Comment by mclaude74** [comment]
Привет, да, в курсе. Много изменений в Настройках из-за реорганизации некоторых пунктов. В остальных приложениях это не так заметно. Планирую добавить в репозиторий доперевод, в первую очередь, для Настроек. На [4pda](https://4pda.ru/forum/index.php?act=post&do=edit_post&f=768&t=913936&p=81705204&st=6580) по мере возможности и готовности выкладываю патчи. Для Настроек патч делаю через "механизм тем" (строки перевода кладутся по пути system/media/theme/default), т.к. пересборка этого приложения не получается корректной (из-за определенных warning), в некоторых ситуациях могут падать приложения. Из минусов патча через "механизм тем" - не работает с Темным режимом.

**Comment by mclaude74** [comment]
Недоперевод из-за того, что перевожу постфактум - после выхода прошивки смотрю изменения и добавляю перевод, который обычно попадает в следующую еженедельку.

**Comment by Glocksss** [comment]
Просто читал информацию ,что для смартфонов котором больше года не будет еженеделок

**Comment by Glocksss** [comment]
А доделать перевод и перезалить прошивки на eu не вариант? Для русскоязычных пользователей?

**Comment by mclaude74** [comment]
Я только доперевожу, в свободное время и на собственном энтузиазме. В команду xiaomi.eu не вхожу. По пересборке, по факту добавления перевода, надо уже обращаться к xiaomi.eu

В идеале, они должны сначала добавить изменения в репозиторий, а пересобирать позже на день-другой, чтобы можно было успеть сделать перевод (и не только на русский язык, так на все языки делается перевод и, исключительно, энтузиастами).

Во всяком случае, в прошивках miroom такой проблемы с недопереводом нет, т.к. они выходят позже.

**Comment by Glocksss** [comment]
Согласен ,но ми рум по моему шлак ,мое имхо

**Comment by mclaude74** [comment]
Какое у тебя устройство и версия Android? Используешь Темный режим?
Ты имел ввиду недоперевод Настроек или еще где?

Для DocumentsUI патч есть, он подходит для еженедельных, вышедших за последние несколько месяцев, выложен на 4pda.
Для Настроек, когда закончу доперевод, выложу патч с использованием "механизма тем". 
Могу отдельно сделать патч с пересобранным приложением Настройки, с внедренным допереводом, но использование - на свой риск.

**Comment by Glocksss** [comment]
Mi 6

**Comment by Glocksss** [comment]
9 эндрю

**Comment by Glocksss** [comment]
Сделай патч с приложением)

**Comment by mclaude74** [comment]
[Патч](https://drive.google.com/open?id=10BsFPuH68Y9Nc-vcxEeIEl3loHloedBX) с приложениями

Settings.apk
MiuiContentCatcher.apk
NotificationCenter.apk
DocumentsUI.apk

покрывает основной недоперевод.

На свой риск. Эти же пересобранные для MI MAX 3 приложения работают нормально.
Можешь либо накатить патч, либо выдернуть из архива приложения и рассовать по нужным папкам, выставив разрешения. Желательно предварительно сделать бэкап заменяемых приложений. Оригинальные приложения, также, можно восстановить накатив прошивку заново.

**Comment by Glocksss** [comment]
Привет,скажи, а завтрашняя версия будет уже с переводом,

**Comment by mclaude74** [comment]
Доперевод, сделанный для 9.7.4 должен попасть в 9.7.11
Если основываться на правках в Словацком репозитории (eu-шники в первую очередь для себя делают), недоперевода в 9.7.11 будет совсем немного, мало новых строк появилось.

**Comment by Glocksss** [comment]
пОНЯЛ,СПАСИБО, патч работает, все хорошо
в родном браузере,когда включаешь подтверждение выхода, строка remember my choice не переведена, вариант исправить,пользуюсь им часто,мазолит глаз)))

**Comment by mclaude74** [comment]
Добавил перевод для строки в Браузере, если повезет, успеет попасть в сборку, как и прочие строки для 9.7.11 из Словацкого репозитория. Обычно уже днем в четверг начинается сборка. 
Заявку закрываю. По другим замеченным недопереводам открывай новую заявку.
