### ISSUE TITLE
Недоперевод2

### ISSUE THREAD

**Issue by Glocksss** [ingbrzy/MA-XML-10-RUSSIAN#55]
Привет, в настройках вместо экрана блокировки lock screen
В этом же меню двойное нажатие для блокировки по английски(double tap to wake turn off screen)

**Comment by mclaude74** [comment]
Привет, да, это новые строки из 9.7.11 
Часть строк добавил еще вчера, на базе словацкого репозитория, но эти правки не успели войти в сборку. Выверю перевод по английскому репозиторию, добавлю недостающие строки.
[Изменения в строках](https://github.com/ingbrzy/Xiaomi.eu-MIUIv10-XML-Compare/commit/ae756784d18ee41f9b69a6e1242669f89e0d690e#diff-63ebb9250f49340aece8d4ac541eaf61), пришедшие с 9.7.11.

**Comment by mclaude74** [comment]
В штатный Браузер доперевод строки "Запомнить выбор" успел попасть? Просто не пользуюсь им.

**Comment by Glocksss** [comment]
еще настройки-центр уведомлений-стиль уведомлений-Expand top notificetion

**Comment by Glocksss** [comment]
перевод браузера не попал

**Comment by Glocksss** [comment]
если есть вариант пересобрать настройки как в тот раз, буду тестером)

**Comment by mclaude74** [comment]
Как закончу с допереводом, соберу.

**Comment by mclaude74** [comment]
[Патч](https://drive.google.com/open?id=1aUua6ArpgS6DFZyenxlMpPha7WLHhVew).

**Comment by Glocksss** [comment]
Спасибо ,в браузере тоже русский,но настройки не как в 9.7.11 порядок немного не тот

**Comment by mclaude74** [comment]
Браузер взят из прошивки 9.7.11 для mi 6, версия 10.8.5
Я не пользуюсь им, не помню, какая версия была в предыдущих прошивках. 
Добавлен только доперевод одной строки. Пересборка на порядок пунктов не должна влиять.
Если только eu-шники как-то по особому собирают своим инструментом, которым ни с кем не делятся.
В текущей прошивке для mi max 3 зависает Калькулятор на операторе "минус". Взял из прошивки для mi 6, работает нормально. Отличаются размером. Написал на форуме, отмораживаются от этой проблемы.  
Заявку закрываем?

**Comment by Glocksss** [comment]
Да
