### ISSUE TITLE
Mi Mix 3 front camera not work

### ISSUE THREAD

**Issue by Tysontl2007** [ingbrzy/MA-XML-10-RUSSIAN#56]
Mi Mix 3 front camera not work

**Comment by mclaude74** [comment]
Какое отношение имеет перевод прошивки к работе камеры? Здесь отмечаются только проблемы перевода. По проблемам в работе программ вопросы надо задавать на форуме xiaomi.eu

**Comment by mclaude74** [comment]
Ответ с форума xiaomi.eu

Actually, "Palm shutter" is a feature we ported from Redmi Note K20 Pro, and while it seems to work on other devices, it caused many side effects:
Portrait mode crashed on multiple devices, and features like Mirror camera, Age & gender and Magic mirror had no effect.
Thus, "Palm shutter" is no longer ported for tomorrow's release. Your camera should be usable again.
